@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImFkcmlAZXhhbXBsZS5jb20iLCJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNzYzMjI4MDU4LCJleHAiOjE3NjMzMTQ0NTh9.UCb2n8kf_H1_uL-MI-mh46C83KtziBniUndFkhQBnRU
### Crear producto
POST {{baseUrl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Telefono celular",
    "description": "Terreneitor 3000 ultimo en tecnology, más rapido que camaron que se duerme",
    "price": 100000,
    "cantidad": 50,
    "imageUrl": "https://example.com/mouse.jpg",
    "categories": [1, 2]
}

### Crear producto con imagen
POST {{baseUrl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Teclado ergonómico",
    "description": "Una teclado ergonómica de alta calidad",
    "price": 10000,
    "available": true,
    "imageUrl": "https://example.com/keyboard.jpg",
    "categories": [3, 5]
}

### Listar todos los productos
GET {{baseUrl}}/products
Authorization: Bearer {{token}}

### Obtener producto por ID
GET {{baseUrl}}/products/2
Authorization: Bearer {{token}}

### Actualizar producto
PATCH {{baseUrl}}/products/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "price": 99000,
    "available": false
}

### Eliminar producto (Ahora lo pruebo)
DELETE {{baseUrl}}/products/1
Authorization: Bearer {{token}}
