@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImFuZ2llY2FiYWwzNUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMxNTczNzMsImV4cCI6MTc2MzI0Mzc3M30.BzI7NpiIzdAUcGFSOMWOl9OqpcJumK0DjsVpzy98Hwg
### Crear un rol
POST {{baseUrl}}/roles
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "ADMIN",
    "descripcion": "Acceso completo al sistema"
}

### Crear otro rol
POST {{baseUrl}}/roles
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "CLIENT",
    "descripcion": "Usuario registrado con permisos básicos"
}

### Listar roles
GET {{baseUrl}}/roles
Authorization: Bearer {{token}}

### Obtener un rol por ID
GET {{baseUrl}}/roles/1
Authorization: Bearer {{token}}

### Actualizar un rol
PATCH {{baseUrl}}/roles/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descripcion": "Puede ver y modificar sus pedidos"
}

### Eliminar un rol
DELETE {{baseUrl}}/roles/3
Authorization: Bearer {{token}}
