@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImFkcmlAZXhhbXBsZS5jb20iLCJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNzYzMjI4MDU4LCJleHAiOjE3NjMzMTQ0NTh9.UCb2n8kf_H1_uL-MI-mh46C83KtziBniUndFkhQBnRU

### Crear usuario
POST {{baseUrl}}/users
Content-Type: application/json

{
    "nombre": "Adriana",
    "apellido": "Caicedo",
    "email": "adri@example.com",
    "telefono": "32000000",
    "password": "12345678"
}

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "angiecabal35@gmail.com",
    "password": "12345678"
}

### Listar todos los usuarios (solo admin)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Obtener un usuario por ID
GET {{baseUrl}}/users/1
Authorization: Bearer {{token}}

### Actualizar un usuario
PATCH {{baseUrl}}/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "telefono": "31099879",
    "password": "sissonidoClaveSegura"
}

### Eliminar un usuario (solo admin)
DELETE {{baseUrl}}/users/9
Authorization: Bearer {{token}}
