@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI3LCJlbWFpbCI6ImRhamFyeXRoaGVybmFuZGV6QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2MzY1NDEyNywiZXhwIjoxNzYzNzQwNTI3fQ.mKxYAm0aWcOVhrjpAZnGD1KHBCjif7GAR8_4XeVCHZE

### Crear usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "nombre": "petroh",
    "apellido": "alsalslas",
    "email": "yumekomuneko@gmail.com",
    "telefono": "3219342929",
    "password": "456123",
    "role": "cliente"
}

### Recuperar Contraseña
### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "yumekomuneko@gmail.com",
    "password": "456123"
}

### Listar todos los usuarios (solo admin)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Obtener un usuario por ID
GET {{baseUrl}}/users/1
Authorization: Bearer {{token}}

### Actualizar un usuario
PATCH {{baseUrl}}/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "telefono": "31099879",
    "password": "sissonidoClaveSegura"
}

### Eliminar un usuario (solo admin)
DELETE {{baseUrl}}/users/9
Authorization: Bearer {{token}}
