@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImFuZ2llY2FiYWwzNUBnbWFpbC5jb20iLCJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNzYzMjQ3ODY4LCJleHAiOjE3NjMzMzQyNjh9.wmPAjDOn00aDMIvcNY7KBgR3Ew6f8JIqK00jZHAd2Mc


### 1. Crear Detalle de Pedido (Solo Admin / Lógica interna)
POST {{baseUrl}}/order-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "orderId": 1,
    "productId": 3,
    "quantity": 2
}


### 2. Obtener Todos los Detalles de Pedidos (Solo Admin)
GET {{baseUrl}}/order-details
Authorization: Bearer {{token}}


### 3. Obtener un Detalle por ID (Funciona con token de CLIENTE o ADMIN)
GET {{baseUrl}}/order-details/28
Authorization: Bearer {{token}}


### 4. Actualizar Cantidad del Detalle (Solo Admin)
PATCH {{baseUrl}}/order-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "quantity": 5
}


### 5. Eliminar Detalle (Solo Admin)
DELETE {{baseUrl}}/order-details/1
Authorization: Bearer {{token}}