@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI3LCJlbWFpbCI6ImRhamFyeXRoaGVybmFuZGV6QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2MzY1NDEyNywiZXhwIjoxNzYzNzQwNTI3fQ.mKxYAm0aWcOVhrjpAZnGD1KHBCjif7GAR8_4XeVCHZE
GET {{baseUrl}}/carts/my
Authorization: Bearer {{token}}

### 1.2. Añadir Producto + Cantidad (CLIENTE)
POST {{baseUrl}}/carts/item
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 3,
    "quantity": 3
}

### 1.3. 🔄 Actualizar Cantidad del Producto 1 (De 2 a 8)
POST {{baseUrl}}/carts/item
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 3,
    "quantity": 2
}

### 1.4. Eliminar Producto 1 con IdProducto del Carrito (CLIENTE)
DELETE {{baseUrl}}/carts/item/4
Authorization: Bearer {{token}}

### 1.5. Finalizar (Checkout) el Carrito (debe fallar si está vacío)

PATCH {{baseUrl}}/carts/checkout
Authorization: Bearer {{token}}

---

### 1.6. Finalizar (Checkout) el Carrito (éxito)
POST {{baseUrl}}/carts/item
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 2,
    "quantity": 1
}

PATCH {{baseUrl}}/carts/checkout
Authorization: Bearer {{token}}

// Las rutas para ADMINS

### Cliente intenta ver todos los carritos
GET {{baseUrl}}/carts
Authorization: Bearer {{token}}


### Administrador ve todos los carritos
// ESPERA: 200 OK
GET {{baseUrl}}/carts
Authorization: Bearer {{adminToken}}


### Administrador ve un carrito específico por ID
// ESPERA: 200 OK (Si existe el carrito con ID 1)
GET {{baseUrl}}/carts/1
Authorization: Bearer {{adminToken}}